services:
  flower_shop:
    build: .
    ports:
      - "8001:5000"
    volumes:
      - ./app:/app
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "mysql_data:/var/lib/mysql"

volumes:
  mysql_data:
    driver: local
